[
    {
        "_id": "formateo",
        "name": "Formateo de equipo",
        "description": "Formateo de PC/laptop con instalacion base y configuracion inicial.",
        "price": 500,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 500,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "ofimatica",
        "name": "Instalacion de ofimatica 2019 / 2021 / 2024",
        "description": "Instalacion y activacion de suite ofimatica para trabajo o escuela.",
        "price": 250,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 250,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "mantenimiento",
        "name": "Mantenimiento preventivo y correctivo",
        "description": "Revision general de software y ajustes para mejorar estabilidad del equipo.",
        "price": 200,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 200,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "recuperacion",
        "name": "Recuperacion de archivos eliminados",
        "description": "Recuperacion de archivos en disco/USB con herramientas de software. $4 por giga",
        "price": 4,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 4,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "creaciongoogle",
        "name": "Creación cuentas Google",
        "description": "Número celular opcional",
        "price": 40,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 40,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "eliminagoogle",
        "name": "Eliminación de cuentas Google",
        "description": "Celular (Android),  $300 - $450",
        "price": 300,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 300,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "formatcelular",
        "name": "formateo de celulares",
        "description": "Teléfono celular (Android / iOS)",
        "price": 80,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 80,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "macropayjoy",
        "name": "Eliminación de macropay y payjoy",
        "description": "Teléfono celular / tablet (Android)",
        "price": 600,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 600,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "downapps",
        "name": "descarga de aplicaciones para celular",
        "description": "Teléfono celular (Android con o sin cuenta / iOS con cuenta) , $30 - $80 (apps libres )",
        "price": 30,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 30,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "cleancellphone",
        "name": "limpieza de celular nivel software",
        "description": "Teléfono celular (Android)",
        "price": 80,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 80,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "antivirus",
        "name": "Instalacion de antivirus",
        "description": "Instalacion, configuracion y escaneo inicial de seguridad.",
        "price": 50,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 120,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "installpdf",
        "name": "Instalacion de lector PDF",
        "description": "Instalacion y configuracion de lector PDF con herramientas basicas.",
        "price": 90,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 90,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "installnavegadores",
        "name": "Instalacion y ajuste de navegadores",
        "description": "Instalacion de navegador principal, extensiones y ajustes iniciales.",
        "price": 50,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 90,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "installmedia",
        "name": "reproductores de video y audio",
        "description": "PC escritorio / laptop, $120 - $250",
        "price": 130,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 130,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "installedit",
        "name": "programas de edición de video y audio",
        "description": "PC escritorio / laptop, $120 - $250",
        "price": 120,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 120,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "revimpresoras",
        "name": "Revision de impresoras",
        "description": "Impresora",
        "price": 100,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 100,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "repimpresora",
        "name": "Reparacion basica de impresora",
        "description": "Diagnostico y ajuste basico de impresora en software y conectividad.",
        "price": 100,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 100,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "passwordwindows",
        "name": "Recuperacion de contrasena de Windows",
        "description": "Proceso de recuperacion o restablecimiento de acceso al sistema.",
        "price": 200,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 200,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "installdiscos",
        "name": "instalación de discos duros / discos de estado solido / disco M2",
        "description": "Unidad SSD, HDD, USB, M2, $100 - $150",
        "price": 100,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 100,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "_id": "backupcontacts",
        "name": "respaldo de contactos",
        "description": "Teléfono celular / PC ",
        "price": 30,
        "category": "tecnicos",
        "mode": "in-person",
        "__v": 0,
        "basePrice": 30,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "homeSurcharge": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "realizapresentacionespp",
        "name": "realización de presentaciones power point",
        "description": "Temas, no de diapositivas, descripción a realizar, $80 - $700",
        "price": 80,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "excell",
        "name": "realización de graficas en Excel",
        "description": "Información a graficar y detalles, $80 - $ 450\n",
        "price": 80,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "paginasweb",
        "name": "Creación de paginas web",
        "description": "Descripción de la página y detalles, $200 - $1200\n",
        "price": 200,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "codigosdev",
        "name": "Creación de código de programación",
        "description": "Descripción de requerimientos, $30 - $250",
        "price": 30,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "createBD",
        "name": "creación de base de datos",
        "description": "Descripción de requerimientos, $100 - $400\n",
        "price": 100,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "asesoriasoffimatica",
        "name": "asesorias de offimatica y programacion",
        "description": "Persona física, $80 hora\n",
        "price": 80,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "usoprograma",
        "name": "uso de algun programa",
        "description": "Persona física, $50 - $120\n",
        "price": 50,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "transcripcion",
        "name": "transcripción de información",
        "description": "Documento en papel / PDF / borradores, etc. $30 - $250\n",
        "price": 30,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "investigaciones",
        "name": "tareas de investigacion",
        "description": "Detalles de la tarea, $10 - $300",
        "price": 10,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "proyectosfinales",
        "name": "proyectos finales",
        "description": "Descripción de proyecto, $250 - $1200\n",
        "price": 250,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "practicasescolares",
        "name": "ayuda con practicas escolares ",
        "description": "Detalles de práctica, $50 - $450",
        "price": 50,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "creacionvideos",
        "name": "creación de videos ",
        "description": "Material opcional imágenes / audio / video, $120 - $600\n",
        "price": 120,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "creacionAudios",
        "name": "creación de pistas de audio",
        "description": "Material opcional, audios / canciones, etc., $100 - $250",
        "price": 100,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "creacionImagen",
        "name": "creacion de imágenes",
        "description": "Material opcional, $30 -$100\n",
        "price": 30,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "convertir",
        "name": "convertir PDFa word o viceversa",
        "description": "Documento a convertir, $10 - $50",
        "price": 10,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "convertirAudios",
        "name": "convertir audios de whatsapp a mp3 y muchos formatos mas",
        "description": "Audios, canciones, $5 - $50",
        "price": 5,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "installEditaores",
        "name": "instalacion de editores de codigo",
        "description": "PC escritorio / laptop\n",
        "price": 50,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "installcapturas",
        "name": "programas para grabar pantalla",
        "description": "PC escritorio / laptop\n",
        "price": 50,
        "category": "educativos",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "downloayoutube",
        "name": "descargar de videos de youtube",
        "description": "Nombre de video / artista opcional, $5  -$50\n",
        "price": 5,
        "category": "entretenimiento",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "downloadmusic",
        "name": "descarga de musica",
        "description": "Nombre de video / artista opcional, $3 - $50",
        "price": 3,
        "category": "entretenimiento",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "downloadpictures",
        "name": "descarga de imágenes",
        "description": "Detalles / descripción de imágenes, $1 -$10",
        "price": 1,
        "category": "entretenimiento",
        "mode": "in-person",
        "__v": 0
    },
    {
        "homeSurcharge": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20,
        "_id": "downpeliculas",
        "name": "descarga de series / anime / peliculas",
        "description": "Detalles de lo requerido, $20 -$500\n",
        "price": 20,
        "category": "entretenimiento",
        "mode": "in-person",
        "__v": 0
    },
    {
        "_id": "svc-1772655144114",
        "name": "Soporte tecnico domicilio QA",
        "description": "Prueba de calculo automatico",
        "price": 300,
        "basePrice": 300,
        "homeSurcharge": 80,
        "category": "tecnicos",
        "mode": "home",
        "__v": 0,
        "remoteDiscountPct": 15,
        "homeExtraPct": 20
    },
    {
        "_id": "tec-remote-optimizacion-pc",
        "__v": 0,
        "basePrice": 350,
        "category": "tecnicos",
        "description": "Limpieza de inicio, mejora de rendimiento, ajustes de sistema y revision general remota.",
        "homeExtraPct": 20,
        "homeSurcharge": 80,
        "mode": "remote",
        "name": "Optimizacion general de PC/Laptop",
        "remoteDiscountPct": 15,
        "price": 350
    },
    {
        "_id": "tec-remote-office",
        "__v": 0,
        "basePrice": 250,
        "category": "tecnicos",
        "description": "Instalacion de paqueteria ofimatica y configuracion inicial para uso diario.",
        "homeExtraPct": 20,
        "homeSurcharge": 80,
        "mode": "remote",
        "name": "Instalacion y configuracion de Office",
        "remoteDiscountPct": 15,
        "price": 250
    },
    {
        "_id": "tec-remote-antivirus",
        "__v": 0,
        "basePrice": 120,
        "category": "tecnicos",
        "description": "Instalacion, configuracion y escaneo inicial con recomendaciones basicas de seguridad.",
        "homeExtraPct": 20,
        "homeSurcharge": 80,
        "mode": "remote",
        "name": "Instalacion y ajuste de antivirus",
        "remoteDiscountPct": 12,
        "price": 120
    },
    {
        "_id": "tec-remote-malware-basico",
        "__v": 0,
        "basePrice": 130,
        "category": "tecnicos",
        "description": "Revision y eliminacion de adware o software no deseado sin intervencion fisica.",
        "homeExtraPct": 25,
        "homeSurcharge": 90,
        "mode": "remote",
        "name": "Limpieza de malware basico",
        "remoteDiscountPct": 10,
        "price": 130
    },
    {
        "_id": "tec-remote-correo-outlook",
        "__v": 0,
        "basePrice": 180,
        "category": "tecnicos",
        "description": "Alta de cuentas, firma, reglas basicas y sincronizacion en cliente de correo.",
        "homeExtraPct": 20,
        "homeSurcharge": 80,
        "mode": "remote",
        "name": "Configuracion de correo y Outlook",
        "remoteDiscountPct": 15,
        "price": 180
    },
    {
        "_id": "tec-remote-backup-nube",
        "__v": 0,
        "basePrice": 260,
        "category": "tecnicos",
        "description": "Organizacion de archivos y configuracion de Google Drive o OneDrive.",
        "homeExtraPct": 20,
        "homeSurcharge": 80,
        "mode": "remote",
        "name": "Respaldo y sincronizacion en la nube",
        "remoteDiscountPct": 15,
        "price": 260
    },
    {
        "_id": "tec-remote-impresora-red",
        "__v": 0,
        "basePrice": 200,
        "category": "tecnicos",
        "description": "Instalacion de drivers, comparticion y prueba de impresion remota en red local.",
        "homeExtraPct": 30,
        "homeSurcharge": 100,
        "mode": "remote",
        "name": "Configuracion de impresora en red",
        "remoteDiscountPct": 10,
        "price": 200
    },
    {
        "_id": "tec-remote-videollamadas",
        "__v": 0,
        "basePrice": 100,
        "category": "tecnicos",
        "description": "Ajuste de audio, video, permisos y recomendaciones para videollamadas estables.",
        "homeExtraPct": 20,
        "homeSurcharge": 80,
        "mode": "remote",
        "name": "Soporte para Zoom/Meet/Teams",
        "remoteDiscountPct": 15,
        "price": 100
    },
    {
        "_id": "tec-remote-drivers-update",
        "__v": 0,
        "basePrice": 230,
        "category": "tecnicos",
        "description": "Revision de controladores criticos y actualizaciones del sistema operativo.",
        "homeExtraPct": 25,
        "homeSurcharge": 90,
        "mode": "remote",
        "name": "Actualizacion de drivers y sistema",
        "remoteDiscountPct": 10,
        "price": 230
    },
    {
        "_id": "tec-remote-cuentas-recuperacion",
        "__v": 0,
        "basePrice": 190,
        "category": "tecnicos",
        "description": "Ayuda en recuperacion de acceso a correo, servicios y cuentas comunes.",
        "homeExtraPct": 20,
        "homeSurcharge": 80,
        "mode": "remote",
        "name": "Recuperacion de cuentas y accesos",
        "remoteDiscountPct": 15,
        "price": 190
    },
    {
        "_id": "tec-remote-asesoria-compra",
        "__v": 0,
        "basePrice": 120,
        "category": "tecnicos",
        "description": "Evaluacion de opciones de hardware, compatibilidad y recomendacion por presupuesto.",
        "homeExtraPct": 20,
        "homeSurcharge": 80,
        "mode": "remote",
        "name": "Asesoria para compra de equipo",
        "remoteDiscountPct": 15,
        "price": 120
    },
    {
        "_id": "tec-remote-mantenimiento-mensual",
        "__v": 0,
        "basePrice": 300,
        "category": "tecnicos",
        "description": "Paquete mensual de optimizacion, revision preventiva y soporte remoto.",
        "homeExtraPct": 20,
        "homeSurcharge": 100,
        "mode": "remote",
        "name": "Mantenimiento remoto mensual",
        "remoteDiscountPct": 15,
        "price": 300
    },
    {
        "_id": "adm-nss-consulta",
        "__v": 0,
        "basePrice": 40,
        "category": "administrativos",
        "description": "Gestion para ubicar o recuperar Numero de Seguridad Social con validacion de datos. si no tiene correo $35 mas",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Consulta y recuperacion de NSS",
        "remoteDiscountPct": 15,
        "price": 40
    },
    {
        "_id": "adm-curp-consulta-correccion",
        "__v": 0,
        "basePrice": 20,
        "category": "administrativos",
        "description": "Asistencia para consulta, descarga y orientacion en correccion de CURP.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Consulta y apoyo para correccion de CURP",
        "remoteDiscountPct": 15,
        "price": 20
    },
    {
        "_id": "adm-antecedentes-no-penales",
        "__v": 0,
        "basePrice": 80,
        "category": "administrativos",
        "description": "Acompanamiento para requisitos, captura y seguimiento del tramite de antecedentes no penales. $40 si trae cuenta",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Tramite de no antecedentes penales",
        "remoteDiscountPct": 10,
        "price": 80
    },
    {
        "_id": "adm-semanas-cotizadas-imss",
        "__v": 0,
        "basePrice": 160,
        "category": "administrativos",
        "description": "Gestion para obtener reporte de semanas cotizadas y orientacion basica de lectura.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Consulta de semanas cotizadas IMSS",
        "remoteDiscountPct": 15
    },
    {
        "_id": "adm-cita-ine",
        "__v": 0,
        "basePrice": 50,
        "category": "administrativos",
        "description": "Busqueda de modulo disponible y programacion de cita INE segun zona y horario.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Agendado de cita INE",
        "remoteDiscountPct": 15,
        "price": 50
    },
    {
        "_id": "adm-cita-rfc-sat",
        "__v": 0,
        "basePrice": 180,
        "category": "administrativos",
        "description": "Programacion de cita para alta, actualizacion u otros tramites de RFC.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Agendado de cita RFC SAT",
        "remoteDiscountPct": 15,
        "price": 180
    },
    {
        "_id": "adm-rfc-constancia-fiscal",
        "__v": 0,
        "basePrice": 480,
        "category": "administrativos",
        "description": "Apoyo para descarga de constancia de situacion fiscal y verificacion de datos.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Descarga de RFC y constancia fiscal",
        "remoteDiscountPct": 15,
        "price": 480
    },
    {
        "_id": "adm-cita-pasaporte",
        "__v": 0,
        "basePrice": 180,
        "category": "administrativos",
        "description": "Asistencia para reunir requisitos y reservar cita de pasaporte.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Agendado de cita para pasaporte",
        "remoteDiscountPct": 15
    },
    {
        "_id": "adm-cita-licencia",
        "__v": 0,
        "basePrice": 160,
        "category": "administrativos",
        "description": "Programacion de cita para tramite de licencia segun disponibilidad de tu estado.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Agendado de cita licencia de conducir",
        "remoteDiscountPct": 15
    },
    {
        "_id": "adm-pago-tenencia-apoyo",
        "__v": 0,
        "basePrice": 35,
        "category": "administrativos",
        "description": "Asistencia para consulta, referencia y proceso de pago de tenencia.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Apoyo para pago de tenencia",
        "remoteDiscountPct": 15,
        "price": 35
    },
    {
        "_id": "adm-correccion-datos-tramites",
        "__v": 0,
        "basePrice": 130,
        "category": "administrativos",
        "description": "Validacion de capturas para evitar rechazos por inconsistencias en datos personales.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Revision y correccion de datos en tramites",
        "remoteDiscountPct": 15
    },
    {
        "_id": "adm-llenado-formatos-gob",
        "__v": 0,
        "basePrice": 40,
        "category": "administrativos",
        "description": "Captura guiada de formatos para tramites frecuentes con revisiones antes de enviar.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Llenado de formatos de gobierno",
        "remoteDiscountPct": 15,
        "price": 40
    },
    {
        "_id": "adm-expediente-digital-tramites",
        "__v": 0,
        "basePrice": 220,
        "category": "administrativos",
        "description": "Organizacion de documentos PDF/imagenes y checklist para tramites recurrentes.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Creacion de expediente digital para tramites",
        "remoteDiscountPct": 15
    },
    {
        "_id": "adm-asesoria-tramites",
        "__v": 0,
        "basePrice": 250,
        "category": "administrativos",
        "description": "Sesion para definir ruta de tramites, requisitos y tiempos por prioridad.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Asesoria integral de tramites",
        "remoteDiscountPct": 15
    },
    {
        "_id": "edu-presentaciones-pro",
        "__v": 0,
        "basePrice": 220,
        "category": "educativos",
        "description": "Presentaciones ejecutivas o escolares con narrativa visual moderna.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Diseno de presentaciones profesionales",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-presentaciones-defensa",
        "__v": 0,
        "basePrice": 260,
        "category": "educativos",
        "description": "Guion, orden de ideas, diapositivas clave y simulacion de exposicion.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Preparacion de presentacion para exposicion o defensa",
        "remoteDiscountPct": 15
    },
    {
        "_id": "edu-web-landing-basica",
        "__v": 0,
        "basePrice": 280,
        "category": "educativos",
        "description": "Pagina web basica para proyecto escolar o presentacion academica.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Creacion de landing page educativa basica",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-web-portafolio",
        "__v": 0,
        "basePrice": 350,
        "category": "educativos",
        "description": "Sitio personal para mostrar proyectos, CV y contacto.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Portafolio web para estudiante",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-excel-formulas",
        "__v": 0,
        "basePrice": 180,
        "category": "educativos",
        "description": "Sesiones practicas de Excel enfocadas a tareas, reportes y proyectos escolares.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Clases de Excel (formulas, tablas y graficas)",
        "remoteDiscountPct": 15
    },
    {
        "_id": "edu-docs-formato-academico",
        "__v": 0,
        "basePrice": 160,
        "category": "educativos",
        "description": "Ajuste de estilo, referencias, tabla de contenido y estructura de documento.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Formato academico en Word (APA/MLA)",
        "remoteDiscountPct": 15
    },
    {
        "_id": "edu-asesoria-programacion-basica",
        "__v": 0,
        "basePrice": 180,
        "category": "educativos",
        "description": "Apoyo para resolver ejercicios y fundamentos de programacion.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Asesoria de programacion basica",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-asesoria-bases-datos",
        "__v": 0,
        "basePrice": 200,
        "category": "educativos",
        "description": "Modelo ER, consultas SQL y ejercicios academicos.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Asesoria de bases de datos",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-correccion-tesis-proyecto",
        "__v": 0,
        "basePrice": 380,
        "category": "educativos",
        "description": "Correccion integral de redaccion, estructura y referencias.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Revision y correccion de proyecto o tesis",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-edicion-video-exposicion",
        "__v": 0,
        "basePrice": 220,
        "category": "educativos",
        "description": "Edicion de material para presentaciones y tareas audiovisuales.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Edicion de video para exposicion",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-mentoria-digital-herramientas",
        "__v": 0,
        "basePrice": 280,
        "category": "educativos",
        "description": "Capacitacion personalizada en herramientas de productividad y aprendizaje.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Mentoria de herramientas digitales",
        "remoteDiscountPct": 15
    },
    {
        "_id": "edu-paquete-entrega-proyecto",
        "__v": 0,
        "basePrice": 420,
        "category": "educativos",
        "description": "Documento + presentacion + checklist final de entrega.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Paquete de entrega de proyecto final",
        "remoteDiscountPct": 20
    },
    {
        "_id": "ent-playlist-curation",
        "__v": 0,
        "basePrice": 90,
        "category": "entretenimiento",
        "description": "Creacion de playlists por estilo, mood, evento o actividad con seleccion personalizada.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Curacion de playlists personalizadas",
        "remoteDiscountPct": 15
    },
    {
        "_id": "ent-video-shorts-edition",
        "__v": 0,
        "basePrice": 50,
        "category": "entretenimiento",
        "description": "Edicion de reels/shorts para uso personal, promociones o contenido casual.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Edicion de videos cortos para redes",
        "remoteDiscountPct": 12,
        "price": 50
    },
    {
        "_id": "ent-karaoke-pack",
        "__v": 0,
        "basePrice": 230,
        "category": "entretenimiento",
        "description": "Preparacion de canciones karaoke con pistas y organizacion por evento.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Paquete karaoke (audio y letra)",
        "remoteDiscountPct": 15,
        "price": 230
    },
    {
        "_id": "ent-movie-night-pack",
        "__v": 0,
        "basePrice": 120,
        "category": "entretenimiento",
        "description": "Curacion de catalogo por genero/edad y guia de reproduccion para evento.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Paquete noche de peliculas",
        "remoteDiscountPct": 15
    },
    {
        "_id": "ent-anime-series-curation",
        "__v": 0,
        "basePrice": 110,
        "category": "entretenimiento",
        "description": "Recomendacion por gustos, lista de episodios y orden sugerido de visualizacion.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Seleccion y curacion de anime y series",
        "remoteDiscountPct": 15
    },
    {
        "_id": "ent-music-conversion-pack",
        "__v": 0,
        "basePrice": 95,
        "category": "entretenimiento",
        "description": "Conversion de formatos y organizacion por carpetas, artistas y playlists.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Conversion y organizacion de musica",
        "remoteDiscountPct": 15
    },
    {
        "_id": "ent-image-pack-social",
        "__v": 0,
        "basePrice": 80,
        "category": "entretenimiento",
        "description": "Selección de imagenes por tema para uso en estados, historias o publicaciones.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Pack de imagenes para redes y estados",
        "remoteDiscountPct": 15
    },
    {
        "_id": "ent-event-content-pack",
        "__v": 0,
        "basePrice": 260,
        "category": "entretenimiento",
        "description": "Musica, imagenes y clips listos para usar en fiesta, reunion o evento tematico.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Paquete de contenido para evento",
        "remoteDiscountPct": 12
    },
    {
        "_id": "ent-streaming-setup",
        "__v": 0,
        "basePrice": 130,
        "category": "entretenimiento",
        "description": "Ajuste de cuentas, perfiles y recomendaciones de uso en plataformas de streaming.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Configuracion de plataformas de streaming",
        "remoteDiscountPct": 15
    },
    {
        "_id": "ent-gaming-launcher-setup",
        "__v": 0,
        "basePrice": 170,
        "category": "entretenimiento",
        "description": "Instalacion y configuracion de launchers, cuentas y ajustes basicos.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Configuracion de launchers de juegos",
        "remoteDiscountPct": 15
    },
    {
        "_id": "tec-home-diagnostico-visita",
        "__v": 0,
        "basePrice": 280,
        "category": "tecnicos",
        "description": "Visita para diagnostico de falla, evaluacion y plan de solucion.",
        "homeExtraPct": 25,
        "homeSurcharge": 120,
        "mode": "home",
        "name": "Diagnostico tecnico a domicilio",
        "remoteDiscountPct": 15
    },
    {
        "_id": "tec-home-config-red",
        "__v": 0,
        "basePrice": 300,
        "category": "tecnicos",
        "description": "Ajuste de modem/router, seguridad y optimizacion basica de red local.",
        "homeExtraPct": 25,
        "homeSurcharge": 120,
        "mode": "home",
        "name": "Configuracion de red WiFi a domicilio",
        "remoteDiscountPct": 15,
        "price": 300
    },
    {
        "_id": "tec-home-migracion-equipo",
        "__v": 0,
        "basePrice": 360,
        "category": "tecnicos",
        "description": "Transferencia de informacion y configuracion inicial en equipo nuevo.",
        "homeExtraPct": 25,
        "homeSurcharge": 130,
        "mode": "home",
        "name": "Migracion de datos entre equipos",
        "remoteDiscountPct": 15
    },
    {
        "_id": "tec-remote-soporte-prioritario",
        "__v": 0,
        "basePrice": 240,
        "category": "tecnicos",
        "description": "Atencion remota rapida para incidentes urgentes de software.",
        "homeExtraPct": 20,
        "homeSurcharge": 80,
        "mode": "remote",
        "name": "Soporte remoto prioritario",
        "remoteDiscountPct": 12
    },
    {
        "_id": "tec-remote-optimiza-juegos",
        "__v": 0,
        "basePrice": 150,
        "category": "tecnicos",
        "description": "Ajustes de sistema y drivers para mejorar rendimiento en gaming.",
        "homeExtraPct": 20,
        "homeSurcharge": 90,
        "mode": "remote",
        "name": "Optimizacion de PC para juegos",
        "remoteDiscountPct": 10,
        "price": 150
    },
    {
        "_id": "tec-inperson-clase-basica-pc",
        "__v": 0,
        "basePrice": 180,
        "category": "tecnicos",
        "description": "Sesion presencial para uso basico de sistema, carpetas y herramientas comunes.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Clase basica de uso de PC",
        "remoteDiscountPct": 15
    },
    {
        "_id": "tec-remote-backup-empresarial",
        "__v": 0,
        "basePrice": 380,
        "category": "tecnicos",
        "description": "Configuracion de estrategia basica de respaldo para informacion critica.",
        "homeExtraPct": 20,
        "homeSurcharge": 100,
        "mode": "remote",
        "name": "Respaldo remoto para negocio pequeno",
        "remoteDiscountPct": 10
    },
    {
        "_id": "tec-inperson-instalacion-impresora",
        "__v": 0,
        "basePrice": 220,
        "category": "tecnicos",
        "description": "Configuracion de impresora y escaner con pruebas de operacion.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Instalacion de impresora multifuncional",
        "remoteDiscountPct": 15
    },
    {
        "_id": "edu-v2-conversion-pdf-word",
        "__v": 0,
        "basePrice": 50,
        "category": "educativos",
        "description": "Conversion y ajuste basico de formato para entrega academica.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Conversion PDF ↔ Word",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-v2-formato-apa-mla",
        "__v": 0,
        "basePrice": 80,
        "category": "educativos",
        "description": "Aplicacion de normas basicas de formato y referencias.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Formato academico APA/MLA basico",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-v2-correccion-estilo",
        "__v": 0,
        "basePrice": 90,
        "category": "educativos",
        "description": "Revision breve de redaccion, ortografia y claridad del texto.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Correccion ortografica y de estilo (corto)",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-v2-transcripcion-breve",
        "__v": 0,
        "basePrice": 100,
        "category": "educativos",
        "description": "Transcripcion de audio o texto corto para tareas y actividades escolares.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Transcripcion breve",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-v2-presentacion-escolar",
        "__v": 0,
        "basePrice": 150,
        "category": "educativos",
        "description": "Diapositivas para exposiciones escolares con estructura clara.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Presentacion escolar basica",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-v2-excel-sesion",
        "__v": 0,
        "basePrice": 160,
        "category": "educativos",
        "description": "Formulas, tablas y graficas para tareas o reportes escolares.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Asesoria Excel (1 sesion)",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-v2-office-sesion",
        "__v": 0,
        "basePrice": 140,
        "category": "educativos",
        "description": "Ayuda guiada para documentos, presentaciones y productividad.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Asesoria Word/PowerPoint (1 sesion)",
        "remoteDiscountPct": 20
    },
    {
        "_id": "edu-v2-investigacion-guiada",
        "__v": 0,
        "basePrice": 140,
        "category": "educativos",
        "description": "Acompañamiento para ordenar contenido y estructura academica.",
        "homeExtraPct": 25,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Investigacion guiada y estructura de tarea",
        "remoteDiscountPct": 20
    },
    {
        "_id": "dis-logo-basico",
        "__v": 0,
        "basePrice": 180,
        "category": "diseno",
        "description": "Logo simple con propuesta inicial, colores y version final en PNG.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Diseno de logo basico",
        "remoteDiscountPct": 20
    },
    {
        "_id": "dis-logo-pro",
        "__v": 0,
        "basePrice": 320,
        "category": "diseno",
        "description": "Concepto de marca con variantes de color, usos y archivos editables.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Diseno de logo profesional",
        "remoteDiscountPct": 15
    },
    {
        "_id": "dis-tarjeta-presentacion",
        "__v": 0,
        "basePrice": 140,
        "category": "diseno",
        "description": "Diseno de tarjeta frente y vuelta lista para imprimir o compartir.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Tarjeta de presentacion digital",
        "remoteDiscountPct": 20
    },
    {
        "_id": "dis-kit-marca-basico",
        "__v": 0,
        "basePrice": 380,
        "category": "diseno",
        "description": "Logo + paleta de color + tipografia recomendada para negocio.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Kit de marca basico",
        "remoteDiscountPct": 15
    },
    {
        "_id": "dis-post-redes-pack",
        "__v": 0,
        "basePrice": 220,
        "category": "diseno",
        "description": "Diseno de publicaciones para Facebook/Instagram con estilo visual uniforme.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Pack de posts para redes",
        "remoteDiscountPct": 20
    },
    {
        "_id": "dis-stories-pack",
        "__v": 0,
        "basePrice": 180,
        "category": "diseno",
        "description": "Historias verticales para promociones, anuncios o contenido recurrente.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Pack de historias para redes",
        "remoteDiscountPct": 20
    },
    {
        "_id": "dis-edicion-imagenes",
        "__v": 0,
        "basePrice": 130,
        "category": "diseno",
        "description": "Retoque basico, recorte, limpieza de fondo y mejora visual.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Edicion de imagenes",
        "remoteDiscountPct": 20
    },
    {
        "_id": "dis-vectorizacion-logo",
        "__v": 0,
        "basePrice": 50,
        "category": "diseno",
        "description": "Conversion de logo a formato vectorial para uso profesional e impresion.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Vectorizacion de logo",
        "remoteDiscountPct": 20,
        "price": 50
    },
    {
        "_id": "dis-mockup-producto",
        "__v": 0,
        "basePrice": 160,
        "category": "diseno",
        "description": "Presentacion visual del diseno aplicado a producto personalizado.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "remote",
        "name": "Mockup de producto (taza/playera/termo)",
        "remoteDiscountPct": 20
    },
    {
        "_id": "dis-identidad-visual-local",
        "__v": 0,
        "basePrice": 450,
        "category": "diseno",
        "description": "Linea visual base para redes, impresos y presencia comercial.",
        "homeExtraPct": 20,
        "homeSurcharge": 0,
        "mode": "in-person",
        "name": "Identidad visual para negocio local",
        "remoteDiscountPct": 15
    }
]